FROM tomcat:8.5-jdk8-openjdk-slim
RUN mkdir /usr/local/tomcat/ROOT && chmod +777 /usr/local/tomcat/ROOT
COPY Config.properties /usr/local/tomcat/ROOT/Config.properties
#RUN apk add --no-cache wget tar   && mkdir /opt/tomcat && wget https://downloads.apache.org/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz && tar xvf apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1
#EXPOSE 8080
#ENTRYPOINT ["/opt/tomcat/bin/catalina.sh", "run"]