FROM maven:3.6.3-openjdk-8-slim
RUN apt update && apt install git  -y && mkdir /webapps /build && git clone https://github.com/integrator-sev/App42PaaS-Java-MySQL-Sample.git /build/
RUN mvn clean install -am  -Dmaven.test.skip -T 1C -f /build/pom.xml
RUN cp /build/target/*.war  /webapps/test.war